name: Test model image

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Model ID to test (e.g. eos3mk2)"
        required: true
        type: string
      ersilia_branch:
        description: "Ersilia branch to install from"
        required: false
        default: "master"
        type: string
      runner:
        description: "Runner label"
        required: true
        default: "ubuntu-latest"
        type: string

jobs:
  test-image-amd64:
    runs-on: ${{ inputs.runner }}
    continue-on-error: true
    outputs:
      passed: ${{ steps.check-result.outcome }}
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"
          auto-activate-base: false

      - name: Install dependencies
        env:
          ERSILIA_BRANCH: ${{ inputs.ersilia_branch }}
        run: |
          conda run -n base python -m pip install "ersilia[test] @ git+https://github.com/ersilia-os/ersilia.git@${ERSILIA_BRANCH}"

      - name: Test AMD64 image
        env:
          MODEL_ID: ${{ inputs.repo_name }}
        run: |
          conda run -n base bash -c "
            ersilia -v test $MODEL_ID --deep --from_dockerhub --version dev-amd64
          "

      - name: Rename test results JSON
        env:
          MODEL_ID: ${{ inputs.repo_name }}
        run: |
          TEST_JSON="${MODEL_ID}-test.json"

          if [[ ! -f "$TEST_JSON" ]]; then
            echo "Error: Test results file $TEST_JSON not found!"
            exit 1
          fi

          mv "$TEST_JSON" "${MODEL_ID}-test-amd64.json"
          echo "TEST_JSON_AMD64=${MODEL_ID}-test-amd64.json" >> "$GITHUB_ENV"

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-report-amd64
          path: ${{ inputs.repo_name }}-test-amd64.json

      - name: Parse test results
        id: check-result
        env:
          MODEL_ID: ${{ inputs.repo_name }}
        run: |
          TEST_JSON="${MODEL_ID}-test-amd64.json"
          echo "Parsing test results from $TEST_JSON"

          TEST_FAILED=$(jq 'recurse | objects | select(map(select(. == false)) | length > 0)' "$TEST_JSON")
          if [[ -n "$TEST_FAILED" ]]; then
            echo "Some tests failed. Stopping workflow."
            exit 1
          fi
